name: fast_sosyo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pdf: ^3.11.1
  flutter_svg: ^2.1.0
  iconify_flutter: ^0.0.7
  dotted_border: ^2.1.0
  confetti: ^0.7.0
  image_picker: 0.8.9
  file_picker: ^8.1.2
  path_provider: ^2.1.5
  signature: ^5.5.0
  share_plus: ^10.1.2
  intl: ^0.19.0
  get: ^4.6.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400 
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Times New Roman
      fonts:
        - asset: assets/fonts/Times-New-Roman.ttf
          weight: 400
